module.exports = {
  TABLE_APONTAMENTO: 'Apontamento',
  TABLE_ATIVIDADES: 'Atividades',
  TABLE_CAUSA: 'Causa',
  TABLE_COMPONENTE: 'Componente',
  TABLE_DADOS_OPERACOES: 'DadosOperacoes',
  TABLE_DEFEITO: 'Defeito',
  TABLE_EPI: 'Epi',
  TABLE_EQUIPAMENTO: 'Equipamento',
  TABLE_EQUIPAMENTOS: 'Equipamentos',
  TABLE_LISTA_OPERACAO: 'Lista_operacao',
  TABLE_LOCAIS: 'Locais',
  TABLE_NIVEL_ACESSO: 'NivelAcesso',
  TABLE_OPERACOES: 'Operacoes',
  TABLE_PRIORIDADE: 'Prioridade',
  TABLE_SETOR: 'Setor',
  TABLE_SINTOMAS: 'Sintomas',
  TABLE_STATUS: 'Status',
  TABLE_TOKEN: 'Token',
  TABLE_USUARIO: 'Usuario',
  TABLE_VERIFICACAO: 'Verificacao',
  TABLE_EQUIPAMENTO_OPERACAO: 'equipamento_operacao',
  TABLE_OPERACAO: 'operacao',
  TABLE_ORDEM_SERVICO: 'ordemServico',
  TABLE_ORDEM_SERVICO_HAS_EPI: 'ordemServico_has_Epi',
  TABLE_ORDEM_SERVICO_HAS_USUARIO: 'ordemServico_has_Usuario',
  TABLE_TIPO_MANUTENCAO: 'tipoManutencao',
};
